import "./styles/globals.css";
import { AuthProvider } from "@/app/multistep-form/context/AuthContext";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        
      >
        <AuthProvider>
        {children}
        </AuthProvider>
      </body>
    </html>
  );
}
